parameters:
  attention_at_blocks: false
  attention_at_convs: false
  batch_size: 64
  coordinate: -1
  embed_dim: 128
  epochs: 500
  kernel_size: 3
  learning_rate: 0.0001
  levels: 7
  max_grad_norm: 1
  max_steps: 1000000
  model_channels: 8
  num_diff_steps: 800
  num_heads: 0
  proj_embed_dim: 512
  scheduler: tanh61
  traj_len: 2000
project: multiscale-turbulence
