parameters:
  attention_at_blocks: false
  attention_at_convs: false
  type: fourier
  batch_size: 192
  coordinate: 0
  embed_dim: 128
  epochs: 500
  kernel_size: 3
  learning_rate: 0.00001
  levels: 4
  max_grad_norm: 1
  max_steps: 5000000
  model_channels: 8
  num_diff_steps: 1000
  num_heads: 0
  proj_embed_dim: 512
  scheduler: tanh61
  traj_len: 2000
project: simple_diff
